// <auto-generated />
namespace PassionProject_Danyal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class passionproject5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(passionproject5));
        
        string IMigrationMetadata.Id
        {
            get { return "202102260402361_passionproject5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
